name: My Jekyll Website

title: ACME Website # setting the title

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:categories/:title/


#variables
description: 'My personal website, built from the scratch by testing css and html features. Made by <a href="https://twitter.com/deomorxsy" target="_blank">@deomorxsy</a>.'
version: '1.1.0'
bar: foo