name: My Jekyll Website

title: ACME Website # setting the title

# Build settings
markdown: kramdown
highlighter: rouge

permalink: /:categories/:title/

# variables
description: 'My old personal blog built from scratch with jekyll, now revived with CI ;D'
version: '1.1.0'
bar: foo

# comments
utterances:
  repo: "deomorxsy/deomorxsy.github.io"
  issue-term: "pathname"
  label: "utteranc.es"
  theme: "gruvbox-dark"
  crossorigin: "anonymous"
