name: My Jekyll Website

title: rstdtmp-proto # setting the title

# Build settings
markdown: kramdown
kramdown:
  parse_block_html: true
  input: GFM
  html_to_native: true
  parse_span_html: true

#kramdown:
  #parse_block_html: true
  #html_to_native: true
#markdown: CommonMark
highlighter: rouge

permalink: /:categories/:title/

# variables
description: 'My old personal blog built from scratch with jekyll, now revived with CI ;D'
version: '1.1.0'
bar: foo

# post tagging
collections:
  tags:
    output: true
    permalink: tags/:path/

# comments
utterances:
  repo: "deomorxsy/deomorxsy.github.io"
  issue-term: "pathname"
  label: "utteranc.es"
  theme: "gruvbox-dark"
  crossorigin: "anonymous"
