source "https://rubygems.org"

gem "jekyll"
gem "jekyll-gist"
# markdown processor
gem "kramdown", ">= 2.5.1"
gem 'kramdown-math-katex', '~> 1.0', '>= 1.0.1'
group :jekyll_plugins do
  gem 'jekyll-commonmark'
end


gem "webrick", "~> 1.9.1"

gem "ffi", "~> 1.17.2"


