name: submodule to gh-pages ci

on:
  workflow_dispatch:

jobs:
  # Build job
  build:
    # <Not provided for brevity>
    # At a minimum this job should upload artifacts using actions/upload-pages-artifact
    runs-on: ubuntu-latest

    steps:
    - name: Clone main repository
      uses: actions/checkout@v4

    - name: Add SSH private keys for submodule repositories
      uses: webfactory/ssh-agent@v0.9.1
      with:
        # setup the deploy key on the private gitmodule repository,
        # then add on the current as a secret
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Clone submodules
      run: |
        cd ./importRepos
        git submodule update --init --recursive --remote
        cp ./${{ secrets.POST_SUBMODULE }}/posts/cs/* ../oldsite/_posts/Tech/
        cp ./${{ secrets.POST_SUBMODULE }}/misc/about/about.md ../oldsite/about.md

        cp -r ./${{ secrets.POST_SUBMODULE }}/assets/* ../oldsite/assets/
        mkdir -p ../oldsite/assets/about/
        cp ./${{ secrets.POST_SUBMODULE }}/misc/about/images/* ../oldsite/assets/about/

    - name: Install dependencies and build site
      run: |
        cd ./oldsite
        sudo apt-get install ruby-full rake
        echo "gem: --user-install" > ~/.gemrc
        #export PATH=$PATH:/home/runner/.local/share/gem/ruby/3.3.0/bin
        export PATH=$PATH:$HOME/.gem/ruby/3.4.6/bin
        gem install bundler jekyll
        bundle config path ~/.gem/
        bundle install
        bundle update
        bundle exec jekyll build
        bundle exec jekyll serve &
        JEKYLL_PID=$!
        sleep 8
        kill $JEKYLL_PID
        cd -

    - name: Fix permissions
      run: |
        chmod -c -R +rX "_site/" | while read line; do
          echo "::warning title=Invalid file permissions automatically fixed::$line"
        done

    - name: Archive production artifacts
      #(jekyll _site dir)
      uses: actions/upload-pages-artifact@v3
      with:
        name: github-pages
        path: ./oldsite/_site/

  # Deploy job
  deploy:
    # Add a dependency to the build job
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 # or specific "vX.X.X" version tag for this action
